name: Playwright Tests

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Create .env file
        run: |
          echo "PROXY_TOKEN=${{ secrets.PROXY_TOKEN }}" >> .env
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env
          echo "AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}" >> .env
          echo "AUTH_COOKIE_NAME=${{ secrets.AUTH_COOKIE_NAME }}" >> .env
          echo "AUTH_EXPIRE_AT=${{ secrets.AUTH_EXPIRE_AT }}" >> .env
          echo "AUTH_USER_REF_ID=${{ secrets.AUTH_USER_REF_ID }}" >> .env
          echo "AUTH_COMPANY_REF_ID=${{ secrets.AUTH_COMPANY_REF_ID }}" >> .env
          echo "ORG_ID=${{ secrets.ORG_ID }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "STORAGE_STATE=playwright/.auth/user.json" >> .env
          echo "COOKIE_DOMAIN=${{ secrets.COOKIE_DOMAIN }}" >> .env
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> .env
          echo "WORKSPACE_NAME=${{ secrets.WORKSPACE_NAME }}" >> .env

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: test-results/
          retention-days: 30

  deploy-report:
    needs: test
    if: always()
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
